210329/sources/kpk_messenger/kpk_messenger/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('mainapp.urls', namespace='main')),

    path('admin/', admin.site.urls),
    path('accounts/',
         include(('django.contrib.auth.urls', 'auth'), namespace='auth')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

210329/sources/kpk_messenger/mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('dialog/show/<int:dialog_pk>/', mainapp.dialog_show, name='dialog_show'),
    path('dialog/create/', mainapp.dialog_create, name='dialog_create'),
    path('user/dialog/create/<int:user_id>/', mainapp.user_dialog_create,
         name='user_dialog_create'),
    path('user/dialog/delete/<int:pk>/', mainapp.dialog_delete,
         name='dialog_delete'),

    path('dialog/member/<int:sender_pk>/message/create/',
         mainapp.DialogMessageCreate.as_view(),
         name='dialog_message_create'),

    path('user/dialog/new/messages/<int:dialog_pk>/',
         mainapp.dialog_new_messages,
         name='dialog_new_messages'),
]

210329/sources/kpk_messenger/mainapp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.functional import cached_property


class Dialog(models.Model):
    created = models.DateTimeField(verbose_name='отправлено',
                                   auto_now_add=True,
                                   db_index=True)
    name = models.CharField(verbose_name='имя', max_length=64, blank=True)

    @cached_property
    def all_members(self):
        return self.members.all()

    def get_messages_all(self):
        return Message.objects.filter(sender__in=self.all_members). \
            select_related('sender__member')

    def get_messages_new(self, user_id=None):
        result = self.get_messages_all().filter(read=False).order_by('created')
        if user_id is None:
            return result
        return result.exclude(sender=self.get_sender(user_id))

    def get_sender(self, user_id):
        return self.all_members.filter(member_id=user_id).first()

    def __str__(self):
        members = User.objects.filter(
            pk__in=self.all_members.values_list('member_id', flat=True)). \
            values_list('username', flat=True)
        result = f'{self.created.strftime("%Y.%m.%d %H:%M")} ' \
                 f'({" - ".join(members)})'
        return result

    class Meta:
        verbose_name = 'диалог'
        verbose_name_plural = 'диалоги'
        ordering = ['-created']


class DialogMemebers(models.Model):
    CREATOR = '0'
    INTERLOCUTOR = '1'

    ROLE_CHOICES = (
        (CREATOR, 'создатель'),
        (INTERLOCUTOR, 'собеседник'),
    )

    dialog = models.ForeignKey(Dialog,
                               verbose_name='диалог',
                               on_delete=models.CASCADE,
                               related_name="members")
    member = models.ForeignKey(User,
                               verbose_name='участник диалога',
                               on_delete=models.CASCADE,
                               related_name="dialogs")
    role = models.CharField(verbose_name='роль',
                            choices=ROLE_CHOICES,
                            max_length=64,
                            db_index=True)

    class Meta:
        ordering = ['dialog', '-role', 'member']


class Message(models.Model):
    sender = models.ForeignKey(DialogMemebers,
                               verbose_name='отправитель',
                               on_delete=models.CASCADE)
    text = models.TextField(verbose_name='сообщение')
    read = models.BooleanField(verbose_name='прочитано', default=False)
    created = models.DateTimeField(verbose_name='отправлено',
                                   auto_now_add=True,
                                   db_index=True)

    def __str__(self):
        return f'{self.sender} ({self.created}):\n\t{self.text[:35]}'

    class Meta:
        verbose_name = 'сообщение'
        verbose_name_plural = 'сообщения'
        ordering = ['-created']

210329/sources/kpk_messenger/mainapp/forms.py
from django.forms import ModelForm, HiddenInput

from mainapp.models import Message


class DialogMessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ('sender', 'text')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            # print(field_name, field)
            if field_name == 'sender':
                field.widget = HiddenInput()

210329/sources/kpk_messenger/mainapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views.generic import CreateView

from mainapp.forms import DialogMessageForm
from mainapp.models import Dialog, DialogMemebers, Message


@login_required
def index(request):
    dialogues = request.user.dialogs.select_related('dialog').all()
    context = {
        'page_title': 'диалоги',
        'dialogues': dialogues,
    }

    return render(request, 'mainapp/index.html', context)


def dialog_show(request, dialog_pk):
    dialog = get_object_or_404(Dialog, pk=dialog_pk)
    sender = dialog.get_sender(request.user.pk)

    context = {
        'page_title': 'диалог',
        'dialog': dialog,
        'sender': sender,
    }

    return render(request, 'mainapp/dialog_show.html', context)


def dialog_create(request):
    dialogues = request.user.dialogs.select_related('dialog').all(). \
        values_list('dialog_id', flat=True)
    interlocutors = DialogMemebers.objects.filter(dialog__in=dialogues). \
        values_list('member_id', flat=True)
    new_interlocutors = User.objects.exclude(pk__in=interlocutors)

    context = {
        'page_title': 'новый диалог',
        'new_interlocutors': new_interlocutors,
    }
    return render(request, 'mainapp/dialog_create.html', context)


def user_dialog_create(request, user_id):
    interlocutor = User.objects.get(pk=user_id)
    dialog = Dialog.objects.create(
        name=interlocutor.username
    )
    DialogMemebers.objects.create(
        dialog=dialog,
        member=request.user,
        role=DialogMemebers.CREATOR
    )
    DialogMemebers.objects.create(
        dialog=dialog,
        # member_id=user_id,
        member=interlocutor,
        role=DialogMemebers.INTERLOCUTOR
    )

    return HttpResponseRedirect(
        reverse('main:dialog_show', kwargs={'dialog_pk': dialog.pk})
    )


# CBV
def dialog_delete(request, pk):
    # instance = Dialog.objects.filter(pk=pk).first()
    instance = get_object_or_404(Dialog, pk=pk)
    instance.delete()
    return HttpResponseRedirect(reverse('main:index'))


# def dialog_message_create(request):
class DialogMessageCreate(CreateView):
    model = Message
    form_class = DialogMessageForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        form = context['form']
        sender_pk = self.request.resolver_match.kwargs['sender_pk']
        # print(context)
        # print(form.fields['sender'].initial)
        # print(dir(form.fields['sender']))
        # print(sender_pk)
        # print(form.initial)
        # form.fields['sender'].initial = sender_pk
        form.initial['sender'] = sender_pk

        return context

    def get_success_url(self):
        # print(self.object.sender.dialog_id)
        # return reverse('main:index')
        return reverse(
            'main:dialog_show',
            kwargs={'dialog_pk': self.object.sender.dialog_id}
        )


def dialog_new_messages(request, dialog_pk):
    if request.is_ajax():
        dialog = Dialog.objects.filter(pk=dialog_pk).first()
        status = False
        new_messages = None
        if dialog:
            status = True
            _new_messages = dialog.get_messages_new(request.user.pk)
            # _new_messages.update(read=True)
            new_messages = [
                {'pk': el.pk,
                 'username': el.sender.member.username,
                 'created': el.created.strftime('%Y.%m.%d %H:%M'),
                 'text': el.text}
                for el in _new_messages
            ]
            print(f'new messgaes {len(new_messages)}, read update')
            _new_messages.update(read=True)

        return JsonResponse({
            'status': status,
            'new_messages': new_messages,
        })

210329/sources/kpk_messenger/mainapp/templates/mainapp/dialog_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ page_title|capfirst }}</title>
</head>
<body>
<div>
    <a href="{% url 'main:index' %}">main</a>
</div>
<h3>Пользователи</h3>
<div class="dialog-members">
    <ul>
        {% for item in new_interlocutors %}
            <li>
                <a href="{% url 'main:user_dialog_create' item.pk %}"
                   style="text-decoration: none;">
                    {{ item.username }}
                </a>
            </li>
        {% endfor %}
    </ul>
</div>
</body>
</html>

210329/sources/kpk_messenger/mainapp/templates/mainapp/dialog_show.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ page_title|capfirst }}</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'js/dialog.js' %}"></script>
</head>
<body>
<div>
    <a href="{% url 'main:index' %}">main</a>
</div>
<h3>Диалог: {{ dialog }}</h3>
<div class="message-create">
    <a href="{% url 'main:dialog_message_create' sender.id %}"
       style="text-decoration: none;">
        сообщение
    </a>
</div>
<div class="dialog-messages">
    <a href="{% url 'main:dialog_new_messages' dialog.id %}"
       style="text-decoration: none;"
       class="dialog-update">
        обновить
    </a>
    <ul class="messages-list">
        {% for item in dialog.get_messages_all %}
            <li class="message-{{ item.pk }}">
                {{ item.sender.member.username }}
                ({{ item.created|date:"Y.m.d H:i" }}) - {{ item.text }}
            </li>
        {% endfor %}
    </ul>
</div>
</body>
</html>

210329/sources/kpk_messenger/mainapp/templates/mainapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ page_title|capfirst }}</title>
</head>
<body>
{% if user.is_authenticated %}
<div>
    <span>{{ user.username }}</span>
    <a href="{% url 'auth:logout' %}">logout</a>
</div>
{% endif %}
<h3>Активные диалоги</h3>
<div class="dialog-create">
    <a href="{% url 'main:dialog_create' %}"
       style="text-decoration: none;">
        новый диалог
    </a>
</div>
<div class="dialogues-list">
    <ul>
        {% for item in dialogues %}
        <li>
            <span class="dialog-link">
                <a href="{% url 'main:dialog_show' item.dialog_id %}"
                   style="text-decoration: none;">
                    {{ item.dialog }}
                </a>
            </span>
            <span class="dialog-delete">
                <a href="{% url 'main:dialog_delete' item.dialog_id %}"
                   style="text-decoration: none;">
                    удалить
                </a>
            </span>
        </li>
        {% endfor %}
    </ul>
</div>
</body>
</html>

210329/sources/kpk_messenger/mainapp/templates/mainapp/message_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ page_title|capfirst }}</title>
</head>
<body>
<div>
    <a href="{% url 'main:index' %}">main</a>
</div>
<h3>Сообщение</h3>
<div class="dialog-message">
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="отправить">
    </form>
</div>
</body>
</html>

210329/sources/kpk_messenger/mainapp/templates/mainapp/show_dialog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ page_title|capfirst }}</title>
</head>
<body>
<div>
    <a href="{% url 'main:index' %}">main</a>
</div>
<h3>Диалог: {{ dialog }}</h3>
<div class="dialog-members">
    <ul>
        {% for item in dialog_members %}
            <li>
                <a href="#"
                   style="text-decoration: none;">
                    {{ item.member.username }}
                </a>
            </li>
        {% endfor %}
    </ul>
</div>
<div class="dialog-messages">
    <ul>
        {% for item in dialog_messages %}
            <li>
                {{ item.sender.member.username }}
                ({{ item.created|date:"Y.m.d H:i" }}) - {{ item.text }}
            </li>
        {% endfor %}
    </ul>
</div>
</body>
</html>